### ISSUE TITLE
S3 Uploads Handler

### ISSUE THREAD

**Issue by jetako** [iterateco/iterate-media#17]
Branch: `upload-handler`

------------

When a file is uploaded to `media.iterate.co/uploads`, we want to handle the s3 event with a lamda function.

### Add the following serverless function:

```
functions:
  uploadsObjectCreated:
    handler: lib/handlers/uploads.objectCreated
    events:
      - s3:
          bucket: media.iterate.co
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
```

### Parse components from the s3 event record key
- The key will have this format: `<APP_ID>/<MEDIA_ID>/<FILE_NAME>`

### Detect the mime type (content type) and file extension.
- Get the content type. Hopefully you can get this from the s3 event. If not, you will have to load the object info from s3.
- If the content type is unknown or equals `application/octet-stream`:
  - Download the s3 object
  - Detect the mime type with the `file-type` npm library. Example:
    ```
    const fileType = require('file-type');

    const info = fileType(buffer);
    let mimeType;

    if (info) {
      mimeType = info.mime;
    }
    ```

### Determine the media type from the mime type:
Media types are `image`, `video` and `document` (we will add audio support later).

Media type -> mime type mappings:
- image: `['image/jpeg', 'image/jpg', 'image/pjpeg', 'image/png', 'image/x-png', 'image/gif']`
- video: `['video/mp4', 'video/m4v', 'video/mov', 'video/quicktime', 'video/3gpp', 'video/x-flv', 'video/x-msvideo']`
- document: default

#### Video
We'll cover video transcoding in another ticket.

#### Image
- Follow the **Storage** instructions below.

#### Document
If the media type is not `image` or `video`, default to `document`
- Follow the **Storage** instructions below.

### Storage
If the media type is `image` or `document`, do the following:
- Update the s3 object `Expires` to be never
- Store the media item in DynamoDb. Example:
```
const Media = require('../services/media');

return Media.create(app.id, mediaId, {
  type: mediaType,
  mime_type: mimeType,
  file_name: fileName,
  status: 'processed'
});
```
